### ISSUE TITLE
to_string and Euros

### ISSUE THREAD

**Issue by HenriMorlaye** [kipcole9/money#43]
I, I noticed that
Money.new(:EUR, 100) |> Money.to_string! 
writes €100
Nobody writes amounts like this in Europe, it's written 100€

**Comment by kipcole9** [comment]
@HenriMorlaye, the formatted output depends on the locale you have set (see `Cldr.set_current_locale/1` or the `:locale` parameter to `Money.to_string/2`.

For example:

```
iex(1)> m = Money.new(:EUR, 100)
#Money<:EUR, 100>
iex(2)> for lang <- ["de", "en", "es", "fr", "it", "pl"] do
...(2)>   IO.puts "Locale: #{lang}  Formatted money: #{Money.to_string! m, locale: lang}"
...(2)> end
Locale: de  Formatted money: 100,00 €
Locale: en  Formatted money: €100.00
Locale: es  Formatted money: 100,00 €
Locale: fr  Formatted money: 100,00 €
Locale: it  Formatted money: 100,00 €
Locale: pl  Formatted money: 100,00 €
[:ok, :ok, :ok, :ok, :ok, :ok]
```
The default locale in `Cldr` is "en-001" (global english).  You can adjust this in your `config.exs` as described in the [readme](https://github.com/kipcole9/money#localised-string-formatting) but note makes it clear this isn't obvious and I'll update the docs immediately.

For your use you may find the following configuration useful to add to your `config.exs`:
```
config :ex_cldr,
  default_locale: "fr",
  locales: ["fr",  "en-GB", "de", "it", "es"],
```

**Comment by kipcole9** [comment]
I have updated the docs so hopefully this is now clearer.  Your feedback would be welcome:

* Added a [section](https://hexdocs.pm/ex_money/readme.html#configuring-locales-to-support-localised-formatting) describing the importance of locale configuration and how to do it

* Updated the [section on api usage](https://hexdocs.pm/ex_money/readme.html#localised-money-formatting) to give examples of locale-specific formatting

**Comment by HenriMorlaye** [comment]
Thanks for the configuration example. I did it then forced recompilation like this:
mix deps.compile ex_cldr --force
It downloads the fr locale. But I still have an error:
The locale "fr" is not known

**Comment by kipcole9** [comment]
Both deps need to be compiled:
```
mix deps.compile ex_cldr --force
mix deps.compile ex_cldr_numbers --force
```
Its not great that this is required to be explicit but I haven't found a good way to make this transparent yet.

**Comment by HenriMorlaye** [comment]
Yes, I just saw your new message, I was trying doing both recompilation and it works now. Thanks again !

**Comment by kipcole9** [comment]
No problem, I appreciate the feedback - its always welcome.  Let me know if there's anything where `Money` falls short of your expectations?
